[workspace]
members = ["crates/*", "sazycimde/ah-sazycimde-iced"]
resolver = "3"

[workspace.dependencies]
stodi = { path = "./crates/stodi" }
ah-sets = { path = "./crates/sets"}

[workspace.lints.rust]
non_camel_case_types = "allow"
