[package]
name = "ah-lojban"
version = "0.1.0"
edition = "2024"

[dependencies]
stodi.workspace = true
ah-sets.workspace = true
ah-tcita.workspace = true
contracts = "0.6.7"
thiserror = "2.0.17"

[lints]
workspace = true
